version: '3.8'
services:
  nexus:
    image: sonatype/nexus3
    container_name: based_nexus
    volumes:
      - nexus_data
    ports:
      - "8081:8081"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:15.2-alpine
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  nexus_data:



