name: Docker Container

run-name: Docker Container -- ${{inputs.version}}

on:
  workflow_dispatch:
    inputs:
      version:
        required: false
        type: string

jobs:
  docker:
    runs-on: ubuntu-24.04
    steps:
      - name: Checout Repo
        uses: actions/checkout@v5

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build & Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/refresher:${{inputs.version}}
