name: Nexus Deploy Pipeline

run-name: Nexus Deploy Pipeline -- ${{github.ref_name}}

on:
  push:

jobs:
  nexus-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Java Version
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 25

      - name: Maven Settings File
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          servers: '[{"id": "maven-snapshots", "username": "${{secrets.NEXUS_USERNAME}}", "password": "${{secrets.NEXUS_PASSWORD}}"}]'
          profiles: '[{"id": "nexus-profile", "properties": {"altDeploymentRepository": "maven-snapshots::${{ secrets.NEXUS_URL }}/repository/maven-snapshots"}}]'
          active_profiles: '["nexus-profile"]'
          output_file: .m2/settings.xml

      - name: Maven Build
        run: mvn clean install -q -Dspring.profiles.active=DEV

      - name: Deploy to Nexus
        run: |
          mvn deploy \
          -Dspring.profiles.active=DEV \
          --batch-mode \
          -DrepositoryId='maven-snapshots' \
          -s '/home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml'


